export default `
<p><span style="font-size: 11pt; color: #545454;">Điểm đến đầu tiên của tớ chính là ngọn hải đăng huyền thoại ở mũi Điện – nơi từng là điểm đón bình minh đầu tiên trên đất Việt.</span></p>
<div id="attachment_51566" class="wp-caption aligncenter"><span style="font-size: 11pt; color: #545454;"><img class="size-full wp-image-51566" src="http://image.pikab.in/unsafe/800x0/https://blog.traveloka.com/source/uploads/sites/9/2019/07/phu-yen-nen-di-dau-1.jpg" sizes="(max-width: 5184px) 100vw, 5184px" srcset="https://blog.traveloka.com/source/uploads/sites/9/2019/07/phu-yen-nen-di-dau-1.jpg 1024w, https://blog.traveloka.com/source/uploads/sites/9/2019/07/phu-yen-nen-di-dau-1-300x200.jpg 300w, https://blog.traveloka.com/source/uploads/sites/9/2019/07/phu-yen-nen-di-dau-1-768x512.jpg 768w, https://blog.traveloka.com/source/uploads/sites/9/2019/07/phu-yen-nen-di-dau-1-640x427.jpg 640w, https://blog.traveloka.com/source/uploads/sites/9/2019/07/phu-yen-nen-di-dau-1-585x390.jpg 585w" alt="phú yên nên đi đâu - hải đăng mũi điện" width="1024" height="683" /></span>
<div class="wp-caption-text"><span style="font-size: 11pt; color: #545454;">Ngọn hải đăng mũi Điện.</span></div>
</div>
<p><span style="font-size: 11pt; color: #545454;">Mũi Điện cách trung tâm thành phố chừng hơn 30 km, khoảng cách cũng gọi là khá xa, nhưng với khung cảnh dọc đường thì tớ chắc chắn các cậu sẽ muốn đi hoài đi hoài luôn cho mà xem. Con đường đến Mũi Điện uốn lượn theo triền núi, một bên là vách núi cao sừng sững, một bên là màu xanh ngắt của nước biển, thi thoảng bắt gặp những đồi cát trắng cao ơi là cao, rồi lại đổ thêm một vài con dốc với núi non trập trùng “tình” hết sức.</span></p>
<div id="attachment_51567" class="wp-caption aligncenter"><span style="font-size: 11pt; color: #545454;"><img class="size-full wp-image-51567" src="http://image.pikab.in/unsafe/800x0/https://blog.traveloka.com/source/uploads/sites/9/2019/07/phu-yen-nen-di-dau-2.jpg" sizes="(max-width: 5184px) 100vw, 5184px" srcset="https://blog.traveloka.com/source/uploads/sites/9/2019/07/phu-yen-nen-di-dau-2.jpg 1024w, https://blog.traveloka.com/source/uploads/sites/9/2019/07/phu-yen-nen-di-dau-2-300x200.jpg 300w, https://blog.traveloka.com/source/uploads/sites/9/2019/07/phu-yen-nen-di-dau-2-768x512.jpg 768w, https://blog.traveloka.com/source/uploads/sites/9/2019/07/phu-yen-nen-di-dau-2-640x427.jpg 640w, https://blog.traveloka.com/source/uploads/sites/9/2019/07/phu-yen-nen-di-dau-2-585x390.jpg 585w" alt="phú yên nên đi đâu - hải đăng mũi điện" width="100%" height="100%" /></span>
<div class="wp-caption-text"><span style="font-size: 11pt; color: #545454;">Nước biển xanh ngắt.</span></div>
</div>

<p><span style="font-size: 11pt; color: #545454;">Chuyến đi lần này đến Phú Yên thật sự là một bước ngoặt trong hành trình khám phá Việt Nam xinh đẹp của tớ. Mọi thứ ở Phú Yên, từ cảnh quan, đến ẩm thực hay con người, mọi thứ đều thật gần gũi và đáng yêu. Tớ giờ đây chẳng còn ngại cái nắng và gió của biển hay chẳng ngại để làn da của mình tối màu đi một chút nữa, bây giờ tớ đã đủ tự tin để tự mình đi hết biển đảo Việt Nam. À, và nhất định tớ cũng sẽ quay lại Phú Yên nữa chứ!</span></p>
<p><span style="font-size: 11pt; color: #545454;"><em>@ Nguồn Traveloka </em></span></p>`
